### PR TITLE
proposed fix for #61 and #61 - Document.ready

### PR DESCRIPTION
**Pull request by catmando**
Document.ready returns a promise.  Did not want to modify behavior of .ready? so as not to create any breaking changes, but perhaps to be consistent with HTTP.get that is what should happen.

Document.ready? now checks to make sure the Document is not already loaded.  It does not use $.isReady since this is not available in Zepto, but instead creates a variable to track this.  

Added test for the Document.ready promise

Updated Docs

### CODE REVIEW

**Comment by catmando** [comment]
just noticed that this was never integrated... could it be... it fixes some bugs in our code

**Comment by elia** [comment]
Seems good to me, but I'd like @adambeynon to review and merge it

**Comment by elia** [comment]
It took a bit, but it finally happened!

**Comment by elia** [comment]
@catmando would you mind adding an entry in the Changelog?

LMK if you can't and I'll do it myself (hopefully taking less time than the life-span of this PR :stuck_out_tongue_closed_eyes:)

**Comment by catmando** [comment]
I will do it, but not today okay?

Mitch VanDuyn
Founder - Catprint.com LLC
The New Approach to Color Printing
585-278-6308 (text and voice to Mitch)
877-228-7768 (customer support - support@catprint.com)

Lets help each other get email under control.
Unless it's an urgent email I process messages once a day.
I also am trying where practical to follow this concept:
http://five.sentenc.es/
For other great ideas see:  GTD
<http://www.43folders.com/2004/09/08/getting-started-with-getting-things-done>,
and 43Folders <http://www.43folders.com/howto>

*For urgent email please include URGENT in the subject.*

**Comment by elia** [comment]
no problem

**Pull request closed without merging**
